-- Restore only the column-level UPDATE privileges that normal members need.
-- RLS continues to restrict each update to auth.uid() = row owner.

revoke update on table public.profiles from authenticated;

grant update (
  username,
  display_name,
  avatar_url,
  bio,
  occupation,
  interests,
  status_message,
  signature,
  last_seen_at,
  location,
  show_activity,
  show_online,
  allow_follow,
  show_followers,
  allow_dm,
  public_birth_day,
  public_birth_month,
  public_birth_year,
  profile_visibility,
  website_url,
  github_url,
  linkedin_url,
  discord_handle,
  cover_url,
  portfolio_url,
  skills,
  technologies,
  signature_type
) on table public.profiles to authenticated;

revoke update on table public.account_settings from authenticated;

grant update (
  birth_date,
  location_private,
  theme,
  language,
  density,
  email_updates,
  content_filter,
  show_birth_day,
  show_birth_year,
  show_location,
  inapp_reply,
  inapp_mention,
  inapp_quote,
  inapp_reaction,
  inapp_follower,
  inapp_dm,
  inapp_moderation,
  email_reply,
  email_mention,
  email_quote,
  email_reaction,
  email_follower,
  email_dm,
  email_moderation,
  email_news,
  push_enabled,
  push_reply,
  push_mention,
  push_quote,
  push_reaction,
  push_follower,
  push_dm,
  push_moderation,
  inapp_watch,
  email_watch,
  push_watch,
  inapp_membership,
  email_membership,
  push_membership
) on table public.account_settings to authenticated;
